spring:
  application:
    name: "ecommerce product"

  web:
    resources:
      static-locations: file:uploads/

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: ecom

  jackson: # Para manejar zona horaria
    time-zone: UTC

  jpa:
    properties:
      hibernate:
        default_schema: ecom

server:
  port: 8080



logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
